// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/dot_product/dot_product.proto

package dot_product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message type for embedding dotProducts vectors to make batching possible
type InferInput struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_V1 []float32              `protobuf:"fixed32,2,rep,packed,name=v1"`
	xxx_hidden_V2 []float32              `protobuf:"fixed32,3,rep,packed,name=v2"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferInput) Reset() {
	*x = InferInput{}
	mi := &file_proto_dot_product_dot_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferInput) ProtoMessage() {}

func (x *InferInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dot_product_dot_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InferInput) GetV1() []float32 {
	if x != nil {
		return x.xxx_hidden_V1
	}
	return nil
}

func (x *InferInput) GetV2() []float32 {
	if x != nil {
		return x.xxx_hidden_V2
	}
	return nil
}

func (x *InferInput) SetV1(v []float32) {
	x.xxx_hidden_V1 = v
}

func (x *InferInput) SetV2(v []float32) {
	x.xxx_hidden_V2 = v
}

type InferInput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	V1 []float32
	V2 []float32
}

func (b0 InferInput_builder) Build() *InferInput {
	m0 := &InferInput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_V1 = b.V1
	x.xxx_hidden_V2 = b.V2
	return m0
}

// Message type for serving of dotProducts that uses avx and fma to accelerate computations
type DotProduct struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Input       *[]*InferInput         `protobuf:"bytes,2,rep,name=input"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DotProduct) Reset() {
	*x = DotProduct{}
	mi := &file_proto_dot_product_dot_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DotProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DotProduct) ProtoMessage() {}

func (x *DotProduct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dot_product_dot_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DotProduct) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *DotProduct) GetInput() []*InferInput {
	if x != nil {
		if x.xxx_hidden_Input != nil {
			return *x.xxx_hidden_Input
		}
	}
	return nil
}

func (x *DotProduct) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DotProduct) SetInput(v []*InferInput) {
	x.xxx_hidden_Input = &v
}

func (x *DotProduct) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DotProduct) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type DotProduct_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id    *string
	Input []*InferInput
}

func (b0 DotProduct_builder) Build() *DotProduct {
	m0 := &DotProduct{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Input = &b.Input
	return m0
}

// Message type for response for dotProducts serving
type DotProductResult struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Result      []float32              `protobuf:"fixed32,2,rep,packed,name=result"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DotProductResult) Reset() {
	*x = DotProductResult{}
	mi := &file_proto_dot_product_dot_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DotProductResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DotProductResult) ProtoMessage() {}

func (x *DotProductResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dot_product_dot_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DotProductResult) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *DotProductResult) GetResult() []float32 {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *DotProductResult) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DotProductResult) SetResult(v []float32) {
	x.xxx_hidden_Result = v
}

func (x *DotProductResult) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DotProductResult) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type DotProductResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     *string
	Result []float32
}

func (b0 DotProductResult_builder) Build() *DotProductResult {
	m0 := &DotProductResult{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Result = b.Result
	return m0
}

var File_proto_dot_product_dot_product_proto protoreflect.FileDescriptor

const file_proto_dot_product_dot_product_proto_rawDesc = "" +
	"\n" +
	"#proto/dot_product/dot_product.proto\x12\vdot_product\x1a!google/protobuf/go_features.proto\",\n" +
	"\n" +
	"InferInput\x12\x0e\n" +
	"\x02v1\x18\x02 \x03(\x02R\x02v1\x12\x0e\n" +
	"\x02v2\x18\x03 \x03(\x02R\x02v2\"R\n" +
	"\n" +
	"DotProduct\x12\x15\n" +
	"\x02id\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x01R\x02id\x12-\n" +
	"\x05input\x18\x02 \x03(\v2\x17.dot_product.InferInputR\x05input\"A\n" +
	"\x10DotProductResult\x12\x15\n" +
	"\x02id\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x01R\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x03(\x02R\x06result2X\n" +
	"\x11DotProductService\x12C\n" +
	"\tCalculate\x12\x17.dot_product.DotProduct\x1a\x1d.dot_product.DotProductResultBVZJgithub.com/bartwild/WSO-scaling-and-ha-in-stateless-apps/proto/dot_product\x92\x03\a\xd2>\x02\x10\x03\b\x01b\beditionsp\xe8\a"

var file_proto_dot_product_dot_product_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_dot_product_dot_product_proto_goTypes = []any{
	(*InferInput)(nil),       // 0: dot_product.InferInput
	(*DotProduct)(nil),       // 1: dot_product.DotProduct
	(*DotProductResult)(nil), // 2: dot_product.DotProductResult
}
var file_proto_dot_product_dot_product_proto_depIdxs = []int32{
	0, // 0: dot_product.DotProduct.input:type_name -> dot_product.InferInput
	1, // 1: dot_product.DotProductService.Calculate:input_type -> dot_product.DotProduct
	2, // 2: dot_product.DotProductService.Calculate:output_type -> dot_product.DotProductResult
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_dot_product_dot_product_proto_init() }
func file_proto_dot_product_dot_product_proto_init() {
	if File_proto_dot_product_dot_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dot_product_dot_product_proto_rawDesc), len(file_proto_dot_product_dot_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dot_product_dot_product_proto_goTypes,
		DependencyIndexes: file_proto_dot_product_dot_product_proto_depIdxs,
		MessageInfos:      file_proto_dot_product_dot_product_proto_msgTypes,
	}.Build()
	File_proto_dot_product_dot_product_proto = out.File
	file_proto_dot_product_dot_product_proto_goTypes = nil
	file_proto_dot_product_dot_product_proto_depIdxs = nil
}
