// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/dot_product/dot_product.proto

package dot_product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DotProductService_Calculate_FullMethodName = "/dot_product.DotProductService/Calculate"
)

// DotProductServiceClient is the client API for DotProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Server definition
type DotProductServiceClient interface {
	// Function that takes 2 products and returns result of dotProduct operation
	// May be used with batches
	Calculate(ctx context.Context, in *DotProduct, opts ...grpc.CallOption) (*DotProductResult, error)
}

type dotProductServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDotProductServiceClient(cc grpc.ClientConnInterface) DotProductServiceClient {
	return &dotProductServiceClient{cc}
}

func (c *dotProductServiceClient) Calculate(ctx context.Context, in *DotProduct, opts ...grpc.CallOption) (*DotProductResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DotProductResult)
	err := c.cc.Invoke(ctx, DotProductService_Calculate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DotProductServiceServer is the server API for DotProductService service.
// All implementations must embed UnimplementedDotProductServiceServer
// for forward compatibility.
//
// Server definition
type DotProductServiceServer interface {
	// Function that takes 2 products and returns result of dotProduct operation
	// May be used with batches
	Calculate(context.Context, *DotProduct) (*DotProductResult, error)
	mustEmbedUnimplementedDotProductServiceServer()
}

// UnimplementedDotProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDotProductServiceServer struct{}

func (UnimplementedDotProductServiceServer) Calculate(context.Context, *DotProduct) (*DotProductResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedDotProductServiceServer) mustEmbedUnimplementedDotProductServiceServer() {}
func (UnimplementedDotProductServiceServer) testEmbeddedByValue()                           {}

// UnsafeDotProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DotProductServiceServer will
// result in compilation errors.
type UnsafeDotProductServiceServer interface {
	mustEmbedUnimplementedDotProductServiceServer()
}

func RegisterDotProductServiceServer(s grpc.ServiceRegistrar, srv DotProductServiceServer) {
	// If the following call panics, it indicates UnimplementedDotProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DotProductService_ServiceDesc, srv)
}

func _DotProductService_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DotProduct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DotProductServiceServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DotProductService_Calculate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DotProductServiceServer).Calculate(ctx, req.(*DotProduct))
	}
	return interceptor(ctx, in, info, handler)
}

// DotProductService_ServiceDesc is the grpc.ServiceDesc for DotProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DotProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dot_product.DotProductService",
	HandlerType: (*DotProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _DotProductService_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dot_product/dot_product.proto",
}
